### ISSUE TITLE
Running results in Broken pipe on Debian Linux

### ISSUE THREAD

**Issue by muhuk** [mattedicksoncom/blender-xatlas#17]
I tried both with `Pack Only` turned on and off, result is the same:

```
Python: Traceback (most recent call last):
  File "/home/muhuk/.config/blender/2.92/scripts/addons/blender_xatlas/__init__.py", line 329, in execute
    Unwrap_Lightmap_Group_Xatlas_2.execute(self, context)
  File "/home/muhuk/.config/blender/2.92/scripts/addons/blender_xatlas/__init__.py", line 513, in execute
    stdin.write(value)
BrokenPipeError: [Errno 32] Broken pipe

location: <unknown location>:-1
```

I'm on Debian Buster (stable), using Blender 2.92 official release and [blender-xatlas 0.8.0](https://github.com/mattedicksoncom/blender-xatlas/releases/tag/v0.0.8).

```bash
$ ls -la ~/.config/blender/2.92/scripts/addons/blender_xatlas/xatlas/
total 284
drwxr-xr-x 2 muhuk muhuk   4096 Mar 10 22:24 .
drwxr-xr-x 4 muhuk muhuk   4096 Mar 10 22:24 ..
-rwxr--r-- 1 muhuk muhuk 280880 Mar 10 22:24 xatlas-blender
```

The scene I am testing has a single object like this (already unwrapped using builtin algo):

![image](https://user-images.githubusercontent.com/40178/110687609-be9d1880-81f1-11eb-891b-de8a12317c0d.png)

**Comment by mattedicksoncom** [comment]
Hi, thanks for reporting the issue.
I'll see if I can recreate it, and find out what's happening ASAP!

**Comment by muhuk** [comment]
I've run the same test on Blender 2.93-beta and got this error:

```
Python: Traceback (most recent call last):
  File "/home/muhuk/.config/blender/2.93/scripts/addons/blender_xatlas/__init__.py", line 329, in execute
    Unwrap_Lightmap_Group_Xatlas_2.execute(self, context)
  File "/home/muhuk/.config/blender/2.93/scripts/addons/blender_xatlas/__init__.py", line 600, in execute
    obTest.obName = safe_dict[obTest.obName] #probably shouldn't just replace it
AttributeError: 'NoneType' object has no attribute 'obName'

location: <unknown location>:-1
```
